version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  spring-api:
    build:
      context: ./AnimalRegistry  # Specify the path to your Spring API Dockerfile
    container_name: my-app
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: mongodb
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: example

  react-app:
    build:
      context: ./animalui  # Specify the path to your React app Dockerfile
    container_name: react-app
    ports:
      - 3000:3000
    depends_on:
      - spring-api
    environment:
      REACT_APP_API_URL: http://spring-api:8081

volumes:
  mongodb-data:
