version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      
  spring-api:
    build:
      context: ./AnimalRegistry  # Specify the path to your Spring API Dockerfile
    container_name: my-app
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017
      SPRING_DATA_MONGODB_DATABASE: animaldb


  react-app:
    build:
      context: ./animalui  # Specify the path to your React app Dockerfile
    container_name: react-app
    ports:
      - 3000:3000
    depends_on:
      - spring-api
    environment:
      REACT_APP_API_URL: http://spring-api:8081

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: my-jaeger
    ports:
      - "16686:16686"
      - "6831:6831/udp"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
